############################################################
# API Services Specifications
swagger: "2.0"
info:
  title: API Demo
  description: A collection of API demo services.
  version: 2.0.0
  contact:
    name: Jason Zhu
    email: jason_zhuyx@hotmail.com
host: localhost:8081
basePath: /api
consumes:
  - application/json
produces:
  - application/json
schemes:
  - http
  - https
tags:
  - name: info
    description: Generic API information


############################################################
# PATHS
paths:

####################
# API info

  ########## /info
  "/info":
    # /info GET
    get:
      tags:
        - info
      summary: Get API info
      description: "Get info of the API Services"
      operationId: getInfo
      x-swagger-router-controller: ml.api_v1
      produces:
        - application/json
      responses:
        "200":
          description: "Successful operation"
          schema:
            $ref: '#/definitions/apiSchema'

  ########## /spec
  "/spec":
    # /spec GET
    get:
      tags:
        - info
      summary: Get API specifications
      description: "Get swagger.yaml as specifications of the API Services."
      operationId: getApiDoc
      x-swagger-router-controller: ml.api_v1
      produces:
        - application/octet-stream
      responses:
        "200":
          description: "Successful operation"
          schema:
            type: file


############################################################
# MODELS DEFINITIONS
definitions:

  ########## Model: ApiSchema ##########
  apiSchema:
    type: object
    description: "ApiSchema provides detailed info of the API service."
    properties:
      name:
        description: "Name of API service."
        example: Demo API Services
        type: string
      version:
        description: "Version of API service."
        example: 2.0.0
        type: string
      "description":
        description: "Description of the API service."
        example: A collection of API demo services.
        type: string
      endpointURL:
        description: "EndpointURL of the API service."
        example: http://localhost:8081/api
        type: string
      environment:
        description: "Deployment environment for the API service."
        example: test
        type: string
      spec:
        description: "Spec of the API service."
        example: http://localhost:8081/api/swagger.json
        type: string


############################################################
# EXTERNAL DOCUMENTATIONS
externalDocs:
  description: Find out more about OpenAPI specification.
  url: https://swagger.io/specification/v2/
